// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYSKoKX1lhKwzxO4wwPuzZH7XrxX5iov0',
    appId: '1:483439172101:web:612a833aa466b0ab1a1a6c',
    messagingSenderId: '483439172101',
    projectId: 'mwfo9e1',
    authDomain: 'mwfo9e1.firebaseapp.com',
    storageBucket: 'mwfo9e1.appspot.com',
    measurementId: 'G-ZBN9B1P7T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBji_qnyk42leK8LsDCriixpVaUg9cAEeE',
    appId: '1:483439172101:android:d813b5c3b07b9dba1a1a6c',
    messagingSenderId: '483439172101',
    projectId: 'mwfo9e1',
    storageBucket: 'mwfo9e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB96mNElaLJRLyzczd6SN6aY4GuUBkFT0c',
    appId: '1:483439172101:ios:7a912feaa0dddf331a1a6c',
    messagingSenderId: '483439172101',
    projectId: 'mwfo9e1',
    storageBucket: 'mwfo9e1.appspot.com',
    iosBundleId: 'com.example.formFlutter09e1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB96mNElaLJRLyzczd6SN6aY4GuUBkFT0c',
    appId: '1:483439172101:ios:7a912feaa0dddf331a1a6c',
    messagingSenderId: '483439172101',
    projectId: 'mwfo9e1',
    storageBucket: 'mwfo9e1.appspot.com',
    iosBundleId: 'com.example.formFlutter09e1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYSKoKX1lhKwzxO4wwPuzZH7XrxX5iov0',
    appId: '1:483439172101:web:e25cf28f741abb411a1a6c',
    messagingSenderId: '483439172101',
    projectId: 'mwfo9e1',
    authDomain: 'mwfo9e1.firebaseapp.com',
    storageBucket: 'mwfo9e1.appspot.com',
    measurementId: 'G-7V1XW1ZM62',
  );
}
